from typing import Any


class Response:
    status_code: int
    def json(self) -> Any: ...


class TestClient:
    def __init__(self, app: Any) -> None: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...
